
  name: pwg
  version: '0.1.0'
  summary: A CLI for generating passwords
  description: |
    A customisable set of command line tools for generating randomised 
    passwords, including pronounceable passwords and passphrases. Different
    types of password can be defined using patterns and can be saved for later
    use, allowing more or less complex passwords to be generated easily 
    depending on your use case.

  grade: devel
  confinement: devmode

  apps:
    pwg:
      command: pwg

  parts:
    pwg:
      plugin: python
      python-version: python3
      requirements: requirements.txt
      source: https://github.com/rddunphy/pwg/archive/v0.1.0.tar.gz
